<a href="https://colab.research.google.com/github/charlie-aashutosh/IIM-INDORE-Python/blob/main/DataPreprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_excel("/content/a1_Dataset_10Percent.xlsx")

In [3]:
data.head()

ID  DemAffl  DemAge DemClusterGroup DemGender    DemReg DemTVReg  \
0  17147654      5.0     NaN             NaN       NaN       NaN      NaN   
1   8415498     15.0     NaN             NaN         M       NaN      NaN   
2  12107603      NaN     NaN             NaN         M  Midlands     East   
3  14400995      8.0    28.0             NaN         F       NaN      NaN   
4  28724674     14.0    67.0             NaN       NaN       NaN      NaN   

  LoyalClass  LoyalSpend  LoyalTime  TargetBuy  
0        Tin        0.01        5.0          0  
1       Gold     8000.00        5.0          1  
2        Tin        0.01        NaN          1  
3        Tin        0.01        NaN          1  
4        Tin        0.01        7.0          0

Data Cleaning

- Dropping columns
- Null values
- Cateogrical values

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22223 entries, 0 to 22222
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   ID               22223 non-null  int64  
 1   DemAffl          21138 non-null  float64
 2   DemAge           20715 non-null  float64
 3   DemClusterGroup  21549 non-null  object 
 4   DemGender        19711 non-null  object 
 5   DemReg           21758 non-null  object 
 6   DemTVReg         21758 non-null  object 
 7   LoyalClass       22223 non-null  object 
 8   LoyalSpend       22223 non-null  float64
 9   LoyalTime        21942 non-null  float64
 10  TargetBuy        22223 non-null  int64  
dtypes: float64(4), int64(2), object(5)
memory usage: 1.9+ MB


In [4]:
#analyse the null values
data.isna().sum()

ID                    0
DemAffl            1085
DemAge             1508
DemClusterGroup     674
DemGender          2512
DemReg              465
DemTVReg            465
LoyalClass            0
LoyalSpend            0
LoyalTime           281
TargetBuy             0
dtype: int64

We can replace the null values with either the mean (when the data is contineous) of the column or with the mode (when the data is discrete) of the column

In [8]:
data['DemAffl']=data['DemAffl'].fillna(data['DemAffl'].mode()[0])
data['DemAge']=data['DemAge'].fillna(data['DemAge'].mean())
data['DemClusterGroup']=data['DemClusterGroup'].fillna(data['DemClusterGroup'].mode()[0])
data['DemGender']=data['DemGender'].fillna(data['DemGender'].mode()[0])
data['DemReg']=data['DemReg'].fillna(data['DemReg'].mode()[0])
data['DemTVReg']=data['DemTVReg'].fillna(data['DemTVReg'].mode()[0])
data['LoyalTime']=data['LoyalTime'].fillna(data['LoyalTime'].mean())

In [9]:
data.head()

ID  DemAffl  DemAge DemClusterGroup DemGender      DemReg DemTVReg  \
0  17147654      5.0    51.0               C         F  South East   London   
1   8415498     15.0    51.0               C         M  South East   London   
2  12107603      8.0    51.0               C         M    Midlands     East   
3  14400995      8.0    28.0               C         F  South East   London   
4  28724674     14.0    67.0               C         F  South East   London   

  LoyalClass  LoyalSpend  LoyalTime  TargetBuy  
0        Tin        0.01    5.00000          0  
1       Gold     8000.00    5.00000          1  
2        Tin        0.01    6.56467          1  
3        Tin        0.01    6.56467          1  
4        Tin        0.01    7.00000          0

In [10]:
data.isna().sum()

ID                 0
DemAffl            0
DemAge             0
DemClusterGroup    0
DemGender          0
DemReg             0
DemTVReg           0
LoyalClass         0
LoyalSpend         0
LoyalTime          0
TargetBuy          0
dtype: int64

Coverting categorical variables to numeric -

- One hot encoding
- Label encoding

In [11]:
data['DemGender'].unique()

array(['F', 'M', 'U'], dtype=object)

In [12]:
data['DemGender']=data['DemGender'].apply({'F':1,'M':2,'U':0}.get) #one hot encoding

In [13]:
data['DemGender'].unique()

array([1, 2, 0])

In [14]:
from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder()

In [15]:
data['DemClusterGroup'].unique()

array(['C', 'B', 'E', 'D', 'F', 'A', 'U'], dtype=object)

In [16]:
data['DemClusterGroup']=label_encoder.fit_transform(data['DemClusterGroup'])

In [17]:
data['DemClusterGroup'].unique()

array([2, 1, 4, 3, 5, 0, 6])

In [18]:
data['DemReg'].unique()

array(['South East', 'Midlands', 'North', 'South West', 'Scottish'],
      dtype=object)

In [ ]:
data['DemReg']=label_encoder.fit_transform(data['DemReg'])

In [20]:
data['DemReg'].unique()

array([3, 0, 1, 4, 2])

In [21]:
data['DemTVReg'].unique()

array(['London', 'East', 'Ulster', 'S & S East', 'Yorkshire',
       'Wales & West', 'N West', 'Midlands', 'S West', 'N East', 'N Scot',
       'C Scotland', 'Border'], dtype=object)

In [22]:
data['DemTVReg']=label_encoder.fit_transform(data['DemTVReg'])

In [23]:
data['DemTVReg'].unique()

array([ 3,  2, 10,  8, 12, 11,  7,  4,  9,  5,  6,  1,  0])

In [24]:
data['LoyalClass'].unique()

array(['Tin', 'Gold', 'Silver', 'Platinum'], dtype=object)

In [25]:
data['LoyalClass']=label_encoder.fit_transform(data['LoyalClass'])

In [26]:
data['LoyalClass'].unique()

array([3, 0, 2, 1])

In [28]:
data.head()

ID  DemAffl  DemAge  DemClusterGroup  DemGender  DemReg  DemTVReg  \
0  17147654      5.0    51.0                2          1       3         3   
1   8415498     15.0    51.0                2          2       3         3   
2  12107603      8.0    51.0                2          2       0         2   
3  14400995      8.0    28.0                2          1       3         3   
4  28724674     14.0    67.0                2          1       3         3   

   LoyalClass  LoyalSpend  LoyalTime  TargetBuy  
0           3        0.01    5.00000          0  
1           0     8000.00    5.00000          1  
2           3        0.01    6.56467          1  
3           3        0.01    6.56467          1  
4           3        0.01    7.00000          0