<a href="https://colab.research.google.com/github/charlie-aashutosh/IIM-INDORE-Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy

In [ ]:
!pip install numpy

In [1]:
import numpy as np #np is the alias name

In [2]:
#convert list --- array and then we will use numpy
my_list=[1,2,3,4,5]

In [3]:
type(my_list)

list

In [4]:
my_array=np.array(my_list) #.array() used to convert list - array

In [5]:
print(my_array) #here o/p is a row and has no columns so it is referred to as a 1D array

[1 2 3 4 5]


In [6]:
type(my_array)

numpy.ndarray

In [7]:
#2 dimentional array
my_list_1=[1,2,3,4,5]
my_list_2=[0,0,1,5,5]
my_list_3=[3,4,5,9,0]

arr=np.array([my_list_1,my_list_2,my_list_3])

In [8]:
print(arr) #2D array

[[1 2 3 4 5]
 [0 0 1 5 5]
 [3 4 5 9 0]]


In [11]:
arr.shape #here 3 indicates number of rows and 5 indicates number of columns

(3, 5)

In [9]:
type(arr)

numpy.ndarray

In [12]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 0],
       [0, 1, 5],
       [5, 3, 4],
       [5, 9, 0]])

In [13]:
arr.reshape(5,4)

ValueError: cannot reshape array of size 15 into shape (5,4)

In [14]:
arr_new=np.array([[1,2,3,4],
 [5,6,7,8],[9,10,11,12]])

In [15]:
print(arr_new)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
arr_new.shape

(3, 4)

In [17]:
new_arr=arr_new.reshape(2,2,3)

In [18]:
print(new_arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [19]:
new_arr.shape

(2, 2, 3)

In [21]:
new_arr=arr_new.reshape(3,2,2)

In [23]:
print(new_arr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [25]:
#basic operations on single array
a=np.array([1,2,3,4,5])

print("add 1 to each element",a+1)

print("subtract 2 from each element",a-2)

print("multiply 5 to each element",a*5)

print("square of each element",a**2)

add 1 to each element [2 3 4 5 6]
subtract 2 from each element [-1  0  1  2  3]
multiply 5 to each element [ 5 10 15 20 25]
square of each element [ 1  4  9 16 25]


In [ ]:
#unary operations
#binary operations