<a href="https://colab.research.google.com/github/charlie-aashutosh/IIM-INDORE-Python/blob/main/Numpy_Complete.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy

In [1]:
!pip install numpy

In [2]:
import numpy as np #np is the alias name

In [3]:
#convert list --- array and then we will use numpy
my_list=[1,2,3,4,5]

In [4]:
type(my_list)

list

In [5]:
my_array=np.array(my_list) #.array() used to convert list - array

In [6]:
print(my_array) #here o/p is a row and has no columns so it is referred to as a 1D array

[1 2 3 4 5]


In [7]:
type(my_array)

numpy.ndarray

In [8]:
#2 dimentional array
my_list_1=[1,2,3,4,5]
my_list_2=[0,0,1,5,5]
my_list_3=[3,4,5,9,0]

arr=np.array([my_list_1,my_list_2,my_list_3])

In [9]:
print(arr) #2D array

[[1 2 3 4 5]
 [0 0 1 5 5]
 [3 4 5 9 0]]


In [10]:
arr.shape #here 3 indicates number of rows and 5 indicates number of columns

(3, 5)

In [11]:
type(arr)

numpy.ndarray

In [12]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 0],
       [0, 1, 5],
       [5, 3, 4],
       [5, 9, 0]])

In [13]:
arr.reshape(5,4)

ValueError: cannot reshape array of size 15 into shape (5,4)

In [14]:
arr_new=np.array([[1,2,3,4],
 [5,6,7,8],[9,10,11,12]])

In [15]:
print(arr_new)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
arr_new.shape

(3, 4)

In [17]:
new_arr=arr_new.reshape(2,2,3)

In [18]:
print(new_arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [19]:
new_arr.shape

(2, 2, 3)

In [23]:
new_arr=arr_new.reshape(3,2,2)

In [24]:
new_arr

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [25]:
arr=np.array([[1,2,3],[4,5,6]])

In [26]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [27]:
flat_arr=arr.flatten()

In [28]:
print(flat_arr)

[1 2 3 4 5 6]


In [29]:
a=np.array([1,2,3,4,5])

print("add 1 to each element",a+1)
print("mul 5 to each element",a*5)
print("sub 2 from each element",a-2)
print("squaring all the elements",a**2)

add 1 to each element [2 3 4 5 6]
mul 5 to each element [ 5 10 15 20 25]
sub 2 from each element [-1  0  1  2  3]
squaring all the elements [ 1  4  9 16 25]


In [30]:
new_arr=np.array([[1,5,7],[4,7,2],[3,1,9]])

In [31]:
print(new_arr)

[[1 5 7]
 [4 7 2]
 [3 1 9]]


In [35]:
print("largest element from the matrix",new_arr.max())
print("smallest element from the matrix",new_arr.min())
print("sum of all the element from the matrix",new_arr.sum())
print("transpose of the matrix",new_arr.T)

largest element from the matrix 9
smallest element from the matrix 1
sum of all the element from the matrix 39
transpose of the matrix [[1 4 3]
 [5 7 1]
 [7 2 9]]


In [37]:
mat_1=np.array([[1,2],[3,4]])
mat_2=np.array([[4,3],[2,1]])

print("adding the metrics together",mat_1+mat_2)
print("multiplication of the metrics together",mat_1*mat_2)

adding the metrics together [[5 5]
 [5 5]]
multiplication of the metrics together [[4 6]
 [6 4]]


In [38]:
print(np.linalg.eig(mat_1)) #eigen values and eigen vectors

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [39]:
np.arange(1,10) #10 will be exclusive in nature and from 1 to 9 we will get the o/p (equally spaced)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.arange(0,15) #step size bydefault is 1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [40]:
np.arange(0,15,3) #here 3 is the step size -- the difference b/w the consequtive o/p

array([ 0,  3,  6,  9, 12])

In [41]:
np.linspace(1,10,50) #here 10 will not be exclusive in nature, and 50 indicates the number of o/p we generate between 1-10

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [42]:
np.linspace(1,10,75)

array([ 1.        ,  1.12162162,  1.24324324,  1.36486486,  1.48648649,
        1.60810811,  1.72972973,  1.85135135,  1.97297297,  2.09459459,
        2.21621622,  2.33783784,  2.45945946,  2.58108108,  2.7027027 ,
        2.82432432,  2.94594595,  3.06756757,  3.18918919,  3.31081081,
        3.43243243,  3.55405405,  3.67567568,  3.7972973 ,  3.91891892,
        4.04054054,  4.16216216,  4.28378378,  4.40540541,  4.52702703,
        4.64864865,  4.77027027,  4.89189189,  5.01351351,  5.13513514,
        5.25675676,  5.37837838,  5.5       ,  5.62162162,  5.74324324,
        5.86486486,  5.98648649,  6.10810811,  6.22972973,  6.35135135,
        6.47297297,  6.59459459,  6.71621622,  6.83783784,  6.95945946,
        7.08108108,  7.2027027 ,  7.32432432,  7.44594595,  7.56756757,
        7.68918919,  7.81081081,  7.93243243,  8.05405405,  8.17567568,
        8.2972973 ,  8.41891892,  8.54054054,  8.66216216,  8.78378378,
        8.90540541,  9.02702703,  9.14864865,  9.27027027,  9.39

In [47]:
np.random.rand(3,4) #here we provide the number of rows and columns and here by default the range is 0-1 (1 being exclusive)

array([[0.96640245, 0.63857382, 0.20159672, 0.19829922],
       [0.78975955, 0.084554  , 0.93430879, 0.23957053],
       [0.98328259, 0.40956584, 0.2823612 , 0.48513569]])

In [50]:
np.random.rand() #between 0-1 we get one random o/p

0.08680894542624062

In [54]:
np.random.randint(1,20,5) #here range is provided from our side i.e. 1-20 (20 exclusive) and 5 indicates the 5 random o/p

array([15, 12,  2, 17, 12])